Errore nella creazione della squadra Error: Field 'updated_at' doesn't have a default value
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'updated_at' doesn't have a default value",
  sql: "INSERT INTO fantasy_teams (user_id, contest_id, total_cost) VALUES ('59', 410, 3.5)"
}
Errore nella creazione della squadra Error: Field 'updated_at' doesn't have a default value
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'updated_at' doesn't have a default value",
  sql: "INSERT INTO fantasy_teams (user_id, contest_id, total_cost) VALUES ('59', 410, 3.5)"
}
Errore nell'elaborazione della richiesta: Error: Nessun fantasy team trovato per questo contest
    at Query.onResult (C:\Users\Administrator\Documents\fantaconclave\fantasyresult.js:76:18)
    at C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\query.js:87:16
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
Errore nell'elaborazione della richiesta: Error: Nessun fantasy team trovato per questo contest
    at Query.onResult (C:\Users\Administrator\Documents\fantaconclave\fantasyresult.js:76:18)
    at C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\query.js:87:16
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
Errore nella creazione della squadra Error: Field 'updated_at' doesn't have a default value
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'updated_at' doesn't have a default value",
  sql: "INSERT INTO fantasy_teams (user_id, contest_id, total_cost) VALUES ('58', 411, 2)"
}
Errore nella creazione della squadra Error: Field 'updated_at' doesn't have a default value
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'updated_at' doesn't have a default value",
  sql: "INSERT INTO fantasy_teams (user_id, contest_id, total_cost) VALUES ('59', 412, 3.5)"
}
Errore nella creazione della squadra Error: Field 'updated_at' doesn't have a default value
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'updated_at' doesn't have a default value",
  sql: "INSERT INTO fantasy_teams (user_id, contest_id, total_cost) VALUES ('59', 413, 3.5)"
}
Errore nella creazione della squadra Error: Field 'updated_at' doesn't have a default value
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'updated_at' doesn't have a default value",
  sql: "INSERT INTO fantasy_teams (user_id, contest_id, total_cost) VALUES ('59', 414, 3.5)"
}
❌ Rollback causa errore: Errore nella creazione della squadra
Dettagli errore: Error: Field 'updated_at' doesn't have a default value
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'updated_at' doesn't have a default value",
  sql: "INSERT INTO fantasy_teams (user_id, contest_id, total_cost) VALUES ('59', 415, 6)"
}
❌ Rollback causa errore: Hai già confermato una squadra per questo contest
❌ Rollback causa errore: Hai già confermato una squadra per questo contest
❌ Rollback causa errore: Hai già confermato una squadra per questo contest
Errore nell'elaborazione della richiesta: Error: Contest non trovato
    at Query.onResult (C:\Users\Administrator\Documents\fantaconclave\fantasyresult.js:54:16)
    at C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\query.js:87:16
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
Errore nella verifica del nome utente: Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation '='
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_CANT_AGGREGATE_2COLLATIONS',
  errno: 1267,
  sqlState: 'HY000',
  sqlMessage: "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation '='",
  sql: "SELECT user_id FROM users WHERE uniquename = 'LittleSweetღ'"
}
Errore INSERT /users: Error: Incorrect string value: '\xE1\x83\xA6' for column 'username' at row 1
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlState: 'HY000',
  sqlMessage: "Incorrect string value: '\\xE1\\x83\\xA6' for column 'username' at row 1",
  sql: '\n' +
    '      INSERT INTO users \n' +
    '        (username, email, teex_balance, is_active, updated_at, avatar, google_id, uniquename, color)\n' +
    '      VALUES \n' +
    "        ('LittleSweetღ', 'pazzadidamon@gmail.com', 500, 1, NOW(), 'https://lh3.googleusercontent.com/a/ACg8ocLhxll1zjwgcp6Jx6l404tKUrl8ZnESv39dg7Udam2a7Gl8r25Q9w=s96-c', '9ycJ7L398bU1mHk58ACGJQBolaq2', 'LittleSweetღ074', 'aa8b26')\n" +
    '    '
}
Errore nella verifica del nome utente: Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation '='
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_CANT_AGGREGATE_2COLLATIONS',
  errno: 1267,
  sqlState: 'HY000',
  sqlMessage: "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation '='",
  sql: "SELECT user_id FROM users WHERE uniquename = 'LittleSweetღ'"
}
Errore INSERT /users: Error: Incorrect string value: '\xE1\x83\xA6' for column 'username' at row 1
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlState: 'HY000',
  sqlMessage: "Incorrect string value: '\\xE1\\x83\\xA6' for column 'username' at row 1",
  sql: '\n' +
    '      INSERT INTO users \n' +
    '        (username, email, teex_balance, is_active, updated_at, avatar, google_id, uniquename, color)\n' +
    '      VALUES \n' +
    "        ('LittleSweetღ', 'pazzadidamon@gmail.com', 500, 1, NOW(), 'https://lh3.googleusercontent.com/a/ACg8ocLhxll1zjwgcp6Jx6l404tKUrl8ZnESv39dg7Udam2a7Gl8r25Q9w=s96-c', '9ycJ7L398bU1mHk58ACGJQBolaq2', 'LittleSweetღ550', 'a5c233')\n" +
    '    '
}
Errore nella verifica del nome utente: Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation '='
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_CANT_AGGREGATE_2COLLATIONS',
  errno: 1267,
  sqlState: 'HY000',
  sqlMessage: "Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation '='",
  sql: "SELECT user_id FROM users WHERE uniquename = 'LittleSweetღ'"
}
Errore INSERT /users: Error: Incorrect string value: '\xE1\x83\xA6' for column 'username' at row 1
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlState: 'HY000',
  sqlMessage: "Incorrect string value: '\\xE1\\x83\\xA6' for column 'username' at row 1",
  sql: '\n' +
    '      INSERT INTO users \n' +
    '        (username, email, teex_balance, is_active, updated_at, avatar, google_id, uniquename, color)\n' +
    '      VALUES \n' +
    "        ('LittleSweetღ', 'pazzadidamon@gmail.com', 500, 1, NOW(), 'https://lh3.googleusercontent.com/a/ACg8ocLhxll1zjwgcp6Jx6l404tKUrl8ZnESv39dg7Udam2a7Gl8r25Q9w=s96-c', '9ycJ7L398bU1mHk58ACGJQBolaq2', 'LittleSweetღ974', '955721')\n" +
    '    '
}
❌ Rollback causa errore: Saldo Teex insufficiente
❌ Rollback causa errore: Stato del contest non valido per la conferma
❌ Rollback causa errore: Stato del contest non valido per la conferma
Errore INSERT /users: Error: Data too long for column 'avatar' at row 1
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'avatar' at row 1",
  sql: '\n' +
    '      INSERT INTO users \n' +
    '        (username, email, teex_balance, is_active, updated_at, avatar, google_id, uniquename, color)\n' +
    '      VALUES \n' +
    "        ('Francesco Baroni', 'fncbrn2@gmail.com', 500, 1, NOW(), 'https://lh3.googleusercontent.com/a-/ALV-UjWS47tBs-_0DN_pF6OA9yJOsJvkdOYMpjWYCVO68P8HduvngtGaiz9Hy9pWqT4vbgvxcSk3EPrQCv3-L0iYUvjuwx6ryZZpDJosOjpTmQocMXsGwG-9FKBcIORkjIypKtcgj8tnUbW7RRITHkgiIB6ASTWT4UPPFfmQJnDWlcCPzaFMfeIjd12DogEtOAgb6-Ia5AbC227bQTxU7SO3kX849WqUjhD-sCGLkcpEgNu8P7Oq91QSBuWRXTjTuQp6Hx7BsqwU6TfhMYQQMG-SHKMZkphPNmYJ4s175eBYZYEoJh3J48k80kALeC2LgFZjz00WTLExrwquJz-1pG1iyIQ5LSHjw_-iKPTDuN5xEKVN_jZqHaWZEwgqA1cIUiJIMjuHpHIWyiJrY6vJPAOT27-a8gVezbLNjZ8xq5v_4K4zBtm47U1qqEoeLCh3ZLMtJ_VKvCg-nzAp9CJabAzKcc3zUmLP1mZ2UCNJFQyexcstu4Xpwu6Qw0umlAweO2CKSP38slYvtwEWfozZ4m_K812jUYib24KMz1hNRzudJlgiJgpgKWhBw4msoGNm9dKHTUOKG1TwdPeo8bzsf2fm9B2bB5z5ORcR8ChfMWSkDIr62nSpx3eCVHDb72FPPwK9vp9BjVkJZt1VqFrYpf_iXqkgLbG7ZnPrhuyJMd9lCZutpR1b232ReFyX2_WJOdF8PoFO3mhksWHCkovbdaOMXc5sz0EvxdzDbw1C1_nFtA_XjD80fW7HDvcdQB8t-07R9bdF6pZwFQS0Zm02ESVGnNRRptECkxZ2vk0NmYjtd55zD30Sp35Hcfp1GYeMc2LNSiKezVQGb9L92X3-vVyp0mXSPMG4z-WKLhh5QawxLanUaH561RphH9D4Bt1HwavSsBxxWQuEgH9Vflke7RmSILV04fl54WHsUWx4zCO8NvkbQX2mrYtpywjeZnAVD2VwaGQNn-c30cEFu_Zwm2c-RvPopBg=s96-c', 'bUSlsLXxAgThgs91sONKQmE91Vd2', 'Francesco Baroni', '9e4011')\n" +
    '    '
}
Errore INSERT /users: Error: Data too long for column 'avatar' at row 1
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'avatar' at row 1",
  sql: '\n' +
    '      INSERT INTO users \n' +
    '        (username, email, teex_balance, is_active, updated_at, avatar, google_id, uniquename, color)\n' +
    '      VALUES \n' +
    "        ('Francesco Baroni', 'fncbrn2@gmail.com', 500, 1, NOW(), 'https://lh3.googleusercontent.com/a-/ALV-UjWS47tBs-_0DN_pF6OA9yJOsJvkdOYMpjWYCVO68P8HduvngtGaiz9Hy9pWqT4vbgvxcSk3EPrQCv3-L0iYUvjuwx6ryZZpDJosOjpTmQocMXsGwG-9FKBcIORkjIypKtcgj8tnUbW7RRITHkgiIB6ASTWT4UPPFfmQJnDWlcCPzaFMfeIjd12DogEtOAgb6-Ia5AbC227bQTxU7SO3kX849WqUjhD-sCGLkcpEgNu8P7Oq91QSBuWRXTjTuQp6Hx7BsqwU6TfhMYQQMG-SHKMZkphPNmYJ4s175eBYZYEoJh3J48k80kALeC2LgFZjz00WTLExrwquJz-1pG1iyIQ5LSHjw_-iKPTDuN5xEKVN_jZqHaWZEwgqA1cIUiJIMjuHpHIWyiJrY6vJPAOT27-a8gVezbLNjZ8xq5v_4K4zBtm47U1qqEoeLCh3ZLMtJ_VKvCg-nzAp9CJabAzKcc3zUmLP1mZ2UCNJFQyexcstu4Xpwu6Qw0umlAweO2CKSP38slYvtwEWfozZ4m_K812jUYib24KMz1hNRzudJlgiJgpgKWhBw4msoGNm9dKHTUOKG1TwdPeo8bzsf2fm9B2bB5z5ORcR8ChfMWSkDIr62nSpx3eCVHDb72FPPwK9vp9BjVkJZt1VqFrYpf_iXqkgLbG7ZnPrhuyJMd9lCZutpR1b232ReFyX2_WJOdF8PoFO3mhksWHCkovbdaOMXc5sz0EvxdzDbw1C1_nFtA_XjD80fW7HDvcdQB8t-07R9bdF6pZwFQS0Zm02ESVGnNRRptECkxZ2vk0NmYjtd55zD30Sp35Hcfp1GYeMc2LNSiKezVQGb9L92X3-vVyp0mXSPMG4z-WKLhh5QawxLanUaH561RphH9D4Bt1HwavSsBxxWQuEgH9Vflke7RmSILV04fl54WHsUWx4zCO8NvkbQX2mrYtpywjeZnAVD2VwaGQNn-c30cEFu_Zwm2c-RvPopBg=s96-c', 'bUSlsLXxAgThgs91sONKQmE91Vd2', 'Francesco Baroni', '323daa')\n" +
    '    '
}
❌ Rollback causa errore: Saldo Teex insufficiente
❌ Rollback causa errore: Saldo Teex insufficiente
❌ Rollback causa errore: Saldo Teex insufficiente
Errore INSERT /users: Error: Data too long for column 'avatar' at row 1
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'avatar' at row 1",
  sql: '\n' +
    '      INSERT INTO users \n' +
    '        (username, email, teex_balance, is_active, updated_at, avatar, google_id, uniquename, color)\n' +
    '      VALUES \n' +
    "        ('Carlotta Pluchino', 'carlottapluc@gmail.com', 500, 1, NOW(), 'https://lh3.googleusercontent.com/a-/ALV-UjWJBjyrUla6ROYQsI2IaZBig_Jgwgyd67IGmUA_u9c48suWHLtyHrYwD7DtoZfZSy-gYWnx4xTUTXz_RwNSNe-DHGBOgHgGTkWM7AHqwQd370Os7aBwqPtOVePVmNmia4BI3S36XgmFPCosu04ipByhiRs43sF_QBIutY8Z_J9a2mbGkhZYEQ1nTYVpQ493D77wIQolaySxWxBvXWQkKO6m8RVT_8EfUmbHQ6tNv_VNBzCam6O_ZY6EpTf3INLVkGCXt2f1V8G07EaQjpx44VjIz_y4dq1mteJvKRayE2M7tE62Sa6WmuxGKCpYR40nG3Fd2I0f1wO4cWEwQcz3Yokd8YWWGHFLk7XK1V34SlkLh0pJRh7S1GjH-pdmNDqcpSkLhRJ4oy5OPt3-lZwemlTIhKZD7K2SCY76vfZzEbqP47pThTSIgLucMIlOHoobq5Otrmb4YAcgV2RJnkyNSU_pvNqM-zNwntqGUjYx3WJSWiVQHBbJ62QCzBk6bVRpRbQ2o5PyeXLPTGOvgIfsFoUZpcPtkGPpTLJ7uKpiF1x9o0GOuvejGkO0adS3VfyBxGY2zSIJXkgWj2DXtkpOoydJUzHDIo0U6wQA55lC-_LcA-o8W4XHUGwRCcx8R3-FETW1VVUdAMALIfAh8ct1OsbWLeBNydmROa9qFwgvXXuZJXhc16DJDfBdpZps6vwus70cuNkXGhdr5j5pYwjAEpNlD3EXmSkCWrGJ7ncJXXGPdsjtz1-raoY4kn1IZ9iiVT7D8VSqRxxZfadwzCAwt_2qGw-UTfszCMX_KxLZCTRhyTsxR_UO1RsyIseI3aTHRA0kPppUBECdkD5dbomklYJj4oLlM_5NNyRmRUT5OcWrBb3cLJSGvF-zbZkvLI_CKBOoAtZuPBNhHX7izHglTBMbXXfYV4vSfUKeaAKjJfX7j4yyK6KzbU9C4qkE5sO-TdbEhSfXG8UuJYiTSez17LnH3dIcvTKSj3g=s96-c', 'Ln341gNUVbO2fidaMrPzPauAK8E3', 'Carlotta Pluchino', '020162')\n" +
    '    '
}
Errore INSERT /users: Error: Data too long for column 'avatar' at row 1
    at Packet.asError (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'avatar' at row 1",
  sql: '\n' +
    '      INSERT INTO users \n' +
    '        (username, email, teex_balance, is_active, updated_at, avatar, google_id, uniquename, color)\n' +
    '      VALUES \n' +
    "        ('Carlotta Pluchino', 'carlottapluc@gmail.com', 500, 1, NOW(), 'https://lh3.googleusercontent.com/a-/ALV-UjWJBjyrUla6ROYQsI2IaZBig_Jgwgyd67IGmUA_u9c48suWHLtyHrYwD7DtoZfZSy-gYWnx4xTUTXz_RwNSNe-DHGBOgHgGTkWM7AHqwQd370Os7aBwqPtOVePVmNmia4BI3S36XgmFPCosu04ipByhiRs43sF_QBIutY8Z_J9a2mbGkhZYEQ1nTYVpQ493D77wIQolaySxWxBvXWQkKO6m8RVT_8EfUmbHQ6tNv_VNBzCam6O_ZY6EpTf3INLVkGCXt2f1V8G07EaQjpx44VjIz_y4dq1mteJvKRayE2M7tE62Sa6WmuxGKCpYR40nG3Fd2I0f1wO4cWEwQcz3Yokd8YWWGHFLk7XK1V34SlkLh0pJRh7S1GjH-pdmNDqcpSkLhRJ4oy5OPt3-lZwemlTIhKZD7K2SCY76vfZzEbqP47pThTSIgLucMIlOHoobq5Otrmb4YAcgV2RJnkyNSU_pvNqM-zNwntqGUjYx3WJSWiVQHBbJ62QCzBk6bVRpRbQ2o5PyeXLPTGOvgIfsFoUZpcPtkGPpTLJ7uKpiF1x9o0GOuvejGkO0adS3VfyBxGY2zSIJXkgWj2DXtkpOoydJUzHDIo0U6wQA55lC-_LcA-o8W4XHUGwRCcx8R3-FETW1VVUdAMALIfAh8ct1OsbWLeBNydmROa9qFwgvXXuZJXhc16DJDfBdpZps6vwus70cuNkXGhdr5j5pYwjAEpNlD3EXmSkCWrGJ7ncJXXGPdsjtz1-raoY4kn1IZ9iiVT7D8VSqRxxZfadwzCAwt_2qGw-UTfszCMX_KxLZCTRhyTsxR_UO1RsyIseI3aTHRA0kPppUBECdkD5dbomklYJj4oLlM_5NNyRmRUT5OcWrBb3cLJSGvF-zbZkvLI_CKBOoAtZuPBNhHX7izHglTBMbXXfYV4vSfUKeaAKjJfX7j4yyK6KzbU9C4qkE5sO-TdbEhSfXG8UuJYiTSez17LnH3dIcvTKSj3g=s96-c', 'Ln341gNUVbO2fidaMrPzPauAK8E3', 'Carlotta Pluchino', '10d0b3')\n" +
    '    '
}
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'cors'
Require stack:
- C:\Users\Administrator\Documents\fantaconclave\adminserver.js
- C:\Users\Administrator\Documents\fantaconclave\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (C:\Users\Administrator\Documents\fantaconclave\adminserver.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1730:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\adminserver.js',
    'C:\\Users\\Administrator\\Documents\\fantaconclave\\index.js'
  ]
}

Node.js v22.15.0
